<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="7230" started-at="2019-06-02T14:08:31Z" finished-at="2019-06-02T14:08:38Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="7230" started-at="2019-06-02T14:08:31Z" finished-at="2019-06-02T14:08:38Z">
      <class name="TestSuite.DashboardTest">
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:TestSuite.DashboardTest@31a5c39e]" name="beforeMethod" is-config="true" duration-ms="6809" started-at="2019-06-02T14:08:31Z" finished-at="2019-06-02T14:08:38Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="FAIL" signature="TC001_LoginWithCorrectCredentials_Test()[pri:0, instance:TestSuite.DashboardTest@31a5c39e]" name="TC001_LoginWithCorrectCredentials_Test" duration-ms="384" started-at="2019-06-02T14:08:38Z" finished-at="2019-06-02T14:08:38Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The message is not displayed as expected expected [TestArchitect ™ - Execution Dashboard] but found [TestArchitect ™]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The message is not displayed as expected expected [TestArchitect ™ - Execution Dashboard] but found [TestArchitect ™]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at TestSuite.DashboardTest.TC001_LoginWithCorrectCredentials_Test(DashboardTest.java:20)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC001_LoginWithCorrectCredentials_Test -->
      </class> <!-- TestSuite.DashboardTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
